"""added fields

Revision ID: 001f74dbe602
Revises: a7a86f621997
Create Date: 2025-03-13 16:49:54.175502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001f74dbe602'
down_revision: Union[str, None] = 'a7a86f621997'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('reviewer_country', sa.String(), nullable=True))
    op.add_column('reviews', sa.Column('reviewer_time_using_app', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'reviewer_time_using_app')
    op.drop_column('reviews', 'reviewer_country')
    # ### end Alembic commands ###
