"""remove unnecessary fields

Revision ID: 9d50ac6fd3a0
Revises: 001f74dbe602
Create Date: 2025-03-15 16:09:49.381675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d50ac6fd3a0'
down_revision: Union[str, None] = '001f74dbe602'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pricing', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('pricing', 'recorded_at')
    op.drop_column('pricing', 'model')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pricing', sa.Column('model', sa.VARCHAR(), nullable=True))
    op.add_column('pricing', sa.Column('recorded_at', sa.DATETIME(), nullable=True))
    op.drop_column('pricing', 'updated_at')
    # ### end Alembic commands ###
